apiVersion: v1
kind: Service
metadata:
  name: {{ template "livy-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Livy.Component }}"
spec:
  ports:
    - name: http
      port: {{ .Values.Livy.ServicePort }}
      targetPort: {{ .Values.Livy.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Livy.Component }}"
  type: {{ .Values.Livy.ServiceType }}
